---
- name: Configure bridge port
  community.routeros.command:
    commands:
      - >-
        :if ([:len [/interface/bridge/port/find interface={{ item.interface }}]] = 0)
        do={ /interface/bridge/port/add bridge={{ mikrotik_bridge_name }}
        interface={{ item.interface }} {{ 'pvid=' ~ item.pvid if item.pvid is defined else '' }} hw=yes }
        else={ /interface/bridge/port/set [find interface={{ item.interface }}]
        bridge={{ mikrotik_bridge_name }} {{ 'pvid=' ~ item.pvid if item.pvid is defined else '' }} hw=yes }
  loop: "{{ mikrotik_bridge_ports }}"
  loop_control:
    label: "{{ item.interface }}"
  changed_when: false

- name: Set comment on bridge port
  community.routeros.command:
    commands:
      - >-
        /interface/bridge/port/set [find interface={{ item.interface }}]
        comment="{{ item.comment }}"
  loop: "{{ mikrotik_bridge_ports | selectattr('comment', 'defined') | list }}"
  loop_control:
    label: "{{ item.interface }}"
  changed_when: false

- name: Set comment on ethernet interface
  community.routeros.command:
    commands:
      - >-
        /interface/ethernet/set [find default-name={{ item.interface }}]
        comment="{{ item.comment }}"
  loop: "{{ mikrotik_bridge_ports | selectattr('comment', 'defined') | list }}"
  loop_control:
    label: "{{ item.interface }}"
  changed_when: false
